### ISSUE TITLE
nats provider push to AzureCR fails due to wrong par name

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/capability-providers#110]
Error:
> Run wash reg push ***/nats:0.11.4 ./nats/build/nats.par.gz -o json
Error: No such file or directory (os error 2)

The rule should use `make target-path` to get the proper name of the par file
(all capability providers have the same target defined so it would be ok to use this for all providers).
`make target-path` returns `build/nats_messaging.par.gz", the path relative to the source folder.
`make target-path-abs` returns the absolute path to the par.gz file.

**Comment by brooksmtownsend** [comment]
Currently, when pushing to our AzureCR, we assume the name of the artifact matches the name in `Cargo.toml` but without the `wasmcloud-provider-` prefix. See [this action](https://github.com/wasmCloud/capability-providers/blob/main/.github/workflows/nats.yml#L85) for the section that is responsible for determining the artifact name _and_ the resulting URL.

Instead, we should be able to publish artifacts to different URLs than their `Cargo.toml` names. This specific issue refers to the `nats` provider which has a different filename than the `Cargo.toml` name. See [this section](https://github.com/wasmCloud/capability-providers/blob/main/nats/Cargo.toml#L32-L34) for why this is.

As @stevelr pointed out, the `make target-path-abs` step should return the absolute path to the `par.gz` file and can be used instead of the combination of the working directory and `${{ env.oci_repository}}` [here](https://github.com/wasmCloud/capability-providers/blob/main/.github/workflows/nats.yml#L92). I'd suggest adding another environment variable in the `Determine artifact metadata` step for the absolute filepath and uploading that.

**Comment by brooksmtownsend** [comment]
This actually was fixed a while ago, not exactly sure where. Closing
