### ISSUE TITLE
Port Filesystem capability provider to OTP

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/capability-providers#115]

**Comment by brooksmtownsend** [comment]
The ability to access the filesystem is a core capability for applications, and for our wasmCloud actors they currently do not have access to this in the current OTP runtime. We have a [filesystem provider](https://github.com/wasmCloud/capability-providers/tree/main/pre-otp/fs) that we wrote with the `wasmcloud:blobstore` interface for pre-otp.

We'd love to reintroduce this capability to actors with the OTP runtime. The blobstore interface deserves some more attention to ensure it offers the proper experience, but creating the smithy interface should be fairly simple because this work has already been done.

Marking this as good first issue as anyone who has experience with Rust should be able to pick up our pre-otp FS provider and transfer that logic over using a combination of `wash new provider` and the [creating a new provider](https://wasmcloud.dev/app-dev/create-provider/) docs

**Comment by matsbror** [comment]
I would be interested in doing this but won't be able to start until next week and can only put part-time effort to it, if that is OK.

**Comment by brooksmtownsend** [comment]
> I would be interested in doing this but won't be able to start until next week and can only put part-time effort to it, if that is OK.

That's definitely okay. Thanks for showing interest in this one! I'll do a little work to make sure you've got the interface resources you need, then I look forward to seeing your progress

**Comment by stevelr** [comment]
I had started writing a `blobstore.smithy` interface a while ago based on the original widl api, and pasted the work in progress into https://github.com/wasmCloud/interfaces/issues/30. Hopefully that can give somebody a head start

**Comment by brooksmtownsend** [comment]
Solved by #154
