### ISSUE TITLE
Not all Key Value stores can implement the keyvalue provider contract

### ISSUE THREAD

**Issue by dylanenabled** [wasmCloud/capability-providers#221]
This project seems like it has a lot of potential but it looks like it has a way to go, and I was looking to contribute based on how I would plan to use wasmCloud.

I was thinking to write a provider for the `wasmcloud:keyvalue` spec that used [NATS Key/Value Store](https://docs.nats.io/nats-concepts/jetstream/key-value-store). I figured this would allow someone who just wants to set up the minimal number of services to use NATS as much as possible until they need something like Redis (if at all).

I quickly realised when looking at the Redis implementation and the contract definition that the contract has a bunch of functions which aren't natively supported by NATS KV Store (like `list_add`, `set_intersection`, etc.) 

NATS pretty much just supports simple CRUD operations on keys so this made it a non-starter.

I then wondered how they were implemented on the Vault `keyvalue` implementation but it has a bunch of "Not Implement" errors for those methods.

This seems to defeat the purpose of having a contract - if your providers can't implement them then user code will fail unless the user knows that the provider doesn't implement those functions, in which case the abstraction is leaky and error prone. 

It seems that perhaps a simpler keyvalue contract should be defined for those providers that just have the basic create/get/update/delete functions?

**Comment by brooksmtownsend** [comment]
Hey @dylanenabled ! This is a great point, and one that we've been considering for a little while. Our keyvalue contract was meant to be pretty complete and since then we've seen a few examples that don't fit the bill.

Because of this, we've started contributing our thoughts to the WebAssembly System interface (WASI) standard keyvalue interface: https://github.com/WebAssembly/wasi-keyvalue. This is a simpler interface that is meant to be the standard for interacting with basic keyvalue stores. Ideally, we'd like to work on interface extensions as well for the specialized operations, but that's still a new idea.

P.S. The [Cosmonic built-in keyvalue](https://cosmonic.com/docs/capabilities/keyvalue/managed) provider is built on top of NATS KV, so it's totally possible to do these operations as it stands today. If it would be of interest, we could look into open sourcing this code to make it available outside of the platform.

**Comment by thomastaylor312** [comment]
Hi there! I am the one who wrote said code! I can definitely see what we can do if you need some helpers of how you could do it yourself. However, we really want to push towards the simpler interface soon as well, so hopefully we'll be able to show some examples of that relatively soon

**Comment by dylanenabled** [comment]
Thanks for the warm welcome guys! Great that you've thought this through already. I wasn't aware of Cosmonic, it looks neat! I'm still just getting across the wasm/wasi ecosystem so thanks for the links @brooksmtownsend. 

I was thinking there are probably ways you could emulate the set and list functions on NATS KV so if open sourcing the Cosmonic keyvalue provider isn't possible, I'd be interested if you could share a blog or something that documents the approach and I could look at implementing that either as a community provider or as part of the core providers if you are interested in integrating it here.

I was thinking you could emulate lists and sets by fetching data from NATS, doing the operation, then storing the data back into the KV store, but that seemed like it would limit the size of the data or could cause performance issues. Maybe I'm prematurely optimising though! I'm sure there are fancier ways to do it as well, but I haven't put a ton of thought into it, so would be interested to hear your approach.

**Comment by thomastaylor312** [comment]
@dylanenabled Sorry this fell off my radar. So we are working on open sourcing some stuff that should allow you to just do this easily, but this is the real trick to how we manage sets and lists:

```rust
//! Types and methods for encoding and decoding data from the KV store

use std::io::{Cursor, Write};

use wasmbus_rpc::error::*;

/// The types of data that can be written
///
/// ## Identifying Data Type
///
/// The data type is indicated by a marker byte at the beginning of the bytes array value. The value
/// of those markers are indicated by the name constants at the top of the file. So, the encoded
/// data should have the marker byte at data[0] and the rest of the data (i.e. data[1..]) is the
/// actual encoded data from the user
// NOTE: enums only support isize, but since these values are controlled by us, we can keep them
// within the range of a u8 for casting.
#[derive(Clone, Copy)]
pub enum DataType {
    Number = 0,
    String = 1,
    Set = 2,
    List = 3,
}

impl DataType {
    pub fn encode_data<S: serde::Serialize>(&self, data: S) -> RpcResult<Vec<u8>> {
        let mut writer = Cursor::new(Vec::new());
        writer
            .write(&[*self as u8])
            .map_err(|e| RpcError::Ser(format!("Unable to write data to buffer: {}", e)))?;
        serde_cbor::to_writer(&mut writer, &data)
            .map_err(|e| RpcError::Ser(format!("Unable to serialize data: {}", e)))?;
        Ok(writer.into_inner())
    }

    pub fn decode_data<'a, D: serde::Deserialize<'a>>(&self, data: &'a [u8]) -> RpcResult<D> {
        self.check_marker(data)?;
        // NOTE(thomastaylor312): With some more massaging of the code, we could make this use
        // from_slice_mut (since we own all data we are passing in here), which requires absolutely 0
        // extra allocations, but I figured that was premature optimization for now
        serde_cbor::from_slice(&data[1..])
            .map_err(|e| RpcError::Deser(format!("Invalid data stored at key: {}", e)))
    }

    fn check_marker(&self, raw: &[u8]) -> RpcResult<()> {
        // Check if the marker byte is correct.
        if let Some(marker) = raw.first() {
            if *marker != *self as u8 {
                Err(RpcError::InvalidParameter(
                    "Invalid operation for data type".to_string(),
                ))
            } else {
                Ok(())
            }
        } else {
            // If there is no first, something is wrong. There should always be at least a marker byte
            Err(RpcError::Other(
                "Data corruption. Found key, but data was entirely empty".to_string(),
            ))
        }
    }
}
```

Essentially there are two steps here:

1. We use a marker byte at the beginning of _all_ data we store inside of nats
2. We use cbor encoding because it is self-describing, but is smaller and faster than JSON

This `DataType` struct can be used like this:

```rust
let data_type = DataType::Set;
// Pretend this has something in it
let my_data = HashSet::new();
data_type.encode_data(my_data)>;
```

You'll even see where I left a comment noting that we could optimize this even further. FWIW, this hasn't caused any huge bottlenecks as of yet, even we we've slammed something writing and reading from the store at several thousand requests per second. 

So, until we start using a new keyvalue contract that doesn't have sets and/or open source some of the stuff we have, this could help you out with the NATS stuff. It also could help when we do have a simpler contract and want to do things like manage sets/lists inside of an actor linked to a kvstore of some kind.

Let me know if this all makes sense!

**Comment by dylanenabled** [comment]
Thanks @thomastaylor312. So from what I understand, when someone say, adds an element to the set, you are reading the whole value from NATS, performing the add operation, and then writing it back. That seems fine for bounded data sizes, and your benchmarking results seem to confirm that. I guess if it becomes a performance concern for unbounded data, Redis can be used instead for the key/value store.

Just to confirm, is open sourcing this extended NATS key/value store on the roadmap? If so I'll drop the implementation from my plans and just wait for what will likely be a superior version :)

Thanks for sharing.

**Comment by thomastaylor312** [comment]
Currently not the whole provider as it has some cosmonic specific things and assumptions that are there for a reason, but we do want to release the wrapper library we put around the normal `Store` from the async_nats library

**Comment by thomastaylor312** [comment]
> So from what I understand, when someone say, adds an element to the set, you are reading the whole value from NATS, performing the add operation, and then writing it back. 

Oh and yes, this is correct. We could optimize it even further with some additional steps, but if you are really going to lean heavily on sets and lists, Redis would likely be a better choice
