### ISSUE TITLE
HTTP Client Actor OP Code

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/capability-providers#58]
When doing the simplest example possible of `httpclient` I was continuously getting `Malformed response from actor` when calling `httpclient::default().request(...)`.  With the assistance of @brooksmtownsend, we where able to narrow in on an OP Code that didn't seem to be consistent throughout the work flow....

https://github.com/wasmCloud/actor-interfaces/blob/main/http-client/rust/src/generated.rs#L61

and

https://github.com/wasmCloud/actor-interfaces/blob/main/http-client/rust/src/lib.rs#L63

appear to be triggering this error everytime

https://github.com/wasmCloud/capability-providers/blob/main/http-client/src/lib.rs#L147

I was able to change https://github.com/wasmCloud/capability-providers/blob/main/http-client/src/lib.rs#L147 to `PerformRequest` and get the actor to behave as expected.

**Comment by jordan-rash** [comment]
From Kevin via slack: 
> the current actor interface uses the operation Request as does the httpclient.widl file. Changing the capability provider to use the operation Request and releasing a new version of it should fix this.

**Comment by brooksmtownsend** [comment]
Yeah we can certainly call the operations whatever we want, I think this is primarily an artifact from upgrading to widl and not meticulously testing (It may have been my fault, there's a lot of little things that can break if you're not careful.)

Recently a pattern that's been working well for me is exporting the operation constants from the `lib` file so that the provider can make use of them directly. This only applies to Rust, as capability providers are written in Rust.

Just changing it to `Request` would work, I think it's worth a small PR to the interface to get the operation fixed too. I can get that whipped up

**Comment by brooksmtownsend** [comment]
Updated the interface to `0.2.0` in https://github.com/wasmCloud/actor-interfaces/pull/68, next step will just be to make that upgrade in the `http-client` provider too, I've changed the operation from `OP_PERFORM_REQUEST` to `OP_REQUEST`

**Comment by brooksmtownsend** [comment]
@jordan-rash do you want to take a stab at that upgrade? Should just require importing the new constant for a request 🙂

**Comment by jordan-rash** [comment]
You want me to write rust?!?!? Challenge accepted

**Comment by brooksmtownsend** [comment]
Closed by #59 , released with #61
