### ISSUE TITLE
Empty Body produces Malformed response (httpserver)

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/capability-providers#66]
When returning an empty body, `wasmcloud` is returning a 500 - Malformed Response Error.  While an empty body doesnt make any sense when returning a 200, it does when returning error states IMO.  I would expect to be able to return an empty body. 

POC:
```
func simpleGet() (httpserver.Response, error) {
    return httpserver.Response{
        StatusCode: 200,
        Status:     "OK",
        Body:       []byte(""),
    }, nil

}

func simplePost() (httpserver.Response, error) {
    return httpserver.Response{
        StatusCode: 200,
        Status:     "OK",
        Body:       []byte("derp"),
    }, nil
}
```
Response from wasmcloud:
```
❯ http GET localhost:8080
HTTP/1.1 500 Internal Server Error
content-length: 29
date: Thu, 01 Apr 2021 18:59:50 GMT

Malformed response from actor

❯ http POST localhost:8080
HTTP/1.1 200 OK
content-length: 4
date: Thu, 01 Apr 2021 18:59:57 GMT

derp
```

**Comment by stevelr** [comment]
tested empty body on httpserver-otp version, and it works.

The tinygo messagepack encoder should be sending an empty array (of length zero). The original bug must have been either with the tinygo code generator or tinygo message pack library. We don't have a tinygo code generator anymore, so if that's where the problem was, then we would close this issue as no longer relevant. I have no doubt that if we added a tinygo code generator that we would test this case with the http server provider, so there's no need to keep this issue open to remind us to test this case in the future.

If the bug is with the tinygo messagepack library, the same thing applies. We will test again when we have a tinygo code generator.
